spring:
  application:
    name: eureka-provider-clustered
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
#      defaultZone: http://eureka-server-1:8761/eureka/, http://eureka-server-2:8762/eureka/
      defaultZone: http://eureka-server-1:8761/eureka/
    healthcheck:
      enabled: true
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 3
logging:
  level:
    root: DEBUG

---
spring:
  profiles: provider-1
server:
  port: 8001
---
spring:
  profiles: provider-2
server:
  port: 8002