spring:
  application:
    name: eureka-server-clustered
eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 3000
  client:
#    registerWithEureka: true
#    fetchRegistry: true
    registerWithEureka: false
    fetchRegistry: false

---
spring:
  profiles: eureka-server-1
server:
  port: 8761
eureka:
  instance:
    hostname: eureka-server-1
  client:
    serviceUrl:
      defaultZone: http://eureka-server-1:8761/eureka/
#      defaultZone: http://eureka-server-2:8762/eureka/

---
spring:
  profiles: eureka-server-2
server:
  port: 8762
eureka:
  instance:
    hostname: eureka-server-2
  client:
    serviceUrl:
      defaultZone: http://eureka-server-1:8761/eureka/